# Generated by Django 5.2.15 on 2026-06-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traderating',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='userblock',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created']},
        ),
    ]
