# Generated by Django 5.2.15 on 2026-06-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_traderating_options_alter_userblock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_trade_distance_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
