# Generated by Django 5.2.15 on 2026-06-06 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMISSIONS_OPEN', 'Submissions Open'), ('WANTLIST_OPEN', 'Want-list Open'), ('MATCHING', 'Matching'), ('MATCH_REVIEW', 'Match Review'), ('FINALIZATION', 'Finalization'), ('SHIPPING', 'Shipping'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('submissions_open_at', models.DateTimeField(blank=True, null=True)),
                ('submissions_close_at', models.DateTimeField(blank=True, null=True)),
                ('wantlist_close_at', models.DateTimeField(blank=True, null=True)),
                ('shipping_rules', models.TextField(blank=True)),
                ('regional_restrictions', models.TextField(blank=True)),
                ('trade_policies', models.TextField(blank=True)),
                ('algorithm_settings', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_organized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=64)),
                ('shipping_pref', models.CharField(blank=True, max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.tradeevent')),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EventListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_listings', to='copies.copy')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='events.tradeevent')),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('event', 'copy')},
            },
        ),
    ]
