# Generated by Django 5.2.15 on 2026-06-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeevent',
            name='matching_mode',
            field=models.CharField(choices=[('ONETOONE', 'Old-school 1-to-1 (online solver)'), ('XTOY', 'X-to-Y (local solver)')], default='ONETOONE', max_length=10),
        ),
    ]
