# Generated by Django 5.2.15 on 2026-06-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_tradeevent_matching_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='max_spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tradeevent',
            name='max_money_per_user',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradeevent',
            name='money_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
