# Generated by Django 5.2.15 on 2026-06-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventparticipation_max_spend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeevent',
            name='center_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeevent',
            name='center_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeevent',
            name='max_distance_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeevent',
            name='require_location',
            field=models.BooleanField(default=False),
        ),
    ]
