# Generated by Django 5.2.15 on 2026-06-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_tradeevent_center_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlisting',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
