# Generated by Django 5.2.15 on 2026-06-13 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventlisting_sell_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeevent',
            name='matching_mode',
        ),
    ]
