# Generated by Django 5.2.15 on 2026-06-21 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_tradeevent_matching_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('combo_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='events.tradeevent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.combo')),
                ('event_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_memberships', to='events.eventlisting')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('combo', 'event_listing')},
            },
        ),
    ]
