# Generated by Django 5.2.15 on 2026-06-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_combo_comboitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeevent',
            name='center_place',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tradeevent',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
