# Generated by Django 5.1.15 on 2026-05-29 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN_SUBMISSIONS', 'Open for submissions'), ('OPEN_WANTLIST', 'Open for want list'), ('MATCHING', 'Matching computation'), ('MATCH_REVIEW', 'Match review'), ('FINALIZED', 'Finalization'), ('SHIPPING', 'Shipping / completion'), ('ARCHIVED', 'Archive')], default='DRAFT', max_length=20)),
                ('region_rule', models.CharField(blank=True, max_length=50)),
                ('allow_bundles', models.BooleanField(default=True)),
                ('submissions_close_at', models.DateTimeField(blank=True, null=True)),
                ('wantlist_close_at', models.DateTimeField(blank=True, null=True)),
                ('max_listings_per_user', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_token', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('ENTERED', 'Entered'), ('WITHDRAWN', 'Withdrawn')], default='ENTERED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_entries', to='inventory.listing')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='events.tradeevent')),
            ],
            options={
                'unique_together': {('event', 'listing')},
            },
        ),
    ]
