# Generated by Django 5.2.15 on 2026-06-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('bgg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('year_published', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, db_index=True, null=True)),
                ('bayes_average', models.FloatField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('users_rated', models.IntegerField(default=0)),
                ('is_expansion', models.BooleanField(default=False)),
                ('category_ranks', models.JSONField(default=dict)),
                ('image_url', models.URLField(blank=True, default='')),
                ('metadata', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank', '-users_rated'],
                'indexes': [models.Index(fields=['rank'], name='catalog_boa_rank_52aba6_idx'), models.Index(fields=['-users_rated'], name='catalog_boa_users_r_5695e9_idx'), models.Index(fields=['name'], name='catalog_boa_name_68d2c1_idx')],
            },
        ),
    ]
