# Generated by Django 5.2.15 on 2026-06-10 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGameVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_version_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=300)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('language', models.CharField(blank=True, default='', max_length=300)),
                ('publisher', models.CharField(blank=True, default='', max_length=500)),
                ('year_published', models.IntegerField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('board_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.boardgame')),
            ],
            options={
                'ordering': ['board_game_id', 'bgg_version_id'],
            },
        ),
    ]
