# Generated by Django 5.2.15 on 2026-06-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_boardgameversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgameversion',
            name='language',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
