# Generated by Django 5.2.15 on 2026-06-06 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('max_give', models.PositiveIntegerField(default=1)),
                ('rules', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_groups', to='events.tradeevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('min_receive', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_groups', to='events.tradeevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TradeWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='events.tradeevent')),
                ('offer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='trades.offergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to=settings.AUTH_USER_MODEL)),
                ('want_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='trades.wantgroup')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WantGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('BOARD_GAME', 'Board Game (any copy)'), ('LISTING', 'Specific Listing')], max_length=20)),
                ('tier', models.PositiveIntegerField(default=1)),
                ('rank', models.IntegerField(default=0)),
                ('board_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='want_group_items', to='catalog.boardgame')),
                ('event_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='want_memberships', to='events.eventlisting')),
                ('want_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trades.wantgroup')),
            ],
            options={
                'ordering': ['tier', 'rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OfferGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_memberships', to='events.eventlisting')),
                ('offer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trades.offergroup')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('offer_group', 'event_listing')},
            },
        ),
    ]
