# Generated by Django 5.2.15 on 2026-06-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wantgroupitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='wantgroupitem',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='wantgroupitem',
            name='tier',
        ),
    ]
