# Generated by Django 5.2.15 on 2026-06-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_wantgroupitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantgroup',
            name='duplicate_protection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wantgroupitem',
            name='money_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
