# Generated by Django 5.2.15 on 2026-06-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_wantgroup_duplicate_protection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offergroupitem',
            name='money_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
