# Generated by Django 5.2.15 on 2026-06-11 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_boardgameversion'),
        ('events', '0005_eventlisting_sell_price'),
        ('trades', '0004_offergroupitem_money_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGamePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('board_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_prices', to='catalog.boardgame')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_prices', to='events.tradeevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('user', 'event', 'board_game')},
            },
        ),
        migrations.CreateModel(
            name='WantBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('BOARD_GAME', 'Board Game (any copy)'), ('LISTING', 'Specific Listing')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('board_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='want_bids', to='catalog.boardgame')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_bids', to='events.tradeevent')),
                ('event_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='want_bids', to='events.eventlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('board_game__isnull', False)), fields=('user', 'event', 'board_game'), name='uniq_wantbid_user_event_game'), models.UniqueConstraint(condition=models.Q(('event_listing__isnull', False)), fields=('user', 'event', 'event_listing'), name='uniq_wantbid_user_event_listing')],
            },
        ),
    ]
