# Generated by Django 5.2.15 on 2026-06-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_usergameprice_wantbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offergroupitem',
            name='money_amount',
        ),
        migrations.RemoveField(
            model_name='wantgroupitem',
            name='money_amount',
        ),
    ]
