# Generated by Django 5.2.15 on 2026-06-21 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_combo_comboitem'),
        ('trades', '0007_remove_board_game_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wantbid',
            name='uniq_wantbid_user_event_listing',
        ),
        migrations.AlterUniqueTogether(
            name='offergroupitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='offergroupitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_memberships', to='events.combo'),
        ),
        migrations.AddField(
            model_name='wantbid',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='want_bids', to='events.combo'),
        ),
        migrations.AddField(
            model_name='wantgroupitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='want_memberships', to='events.combo'),
        ),
        migrations.AlterField(
            model_name='offergroupitem',
            name='event_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_memberships', to='events.eventlisting'),
        ),
        migrations.AlterField(
            model_name='wantbid',
            name='event_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='want_bids', to='events.eventlisting'),
        ),
        migrations.AlterField(
            model_name='wantgroupitem',
            name='event_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='want_memberships', to='events.eventlisting'),
        ),
        migrations.AddConstraint(
            model_name='offergroupitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_listing__isnull', False), ('combo__isnull', True)), models.Q(('event_listing__isnull', True), ('combo__isnull', False)), _connector='OR'), name='offeritem_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='offergroupitem',
            constraint=models.UniqueConstraint(condition=models.Q(('event_listing__isnull', False)), fields=('offer_group', 'event_listing'), name='uniq_offeritem_group_listing'),
        ),
        migrations.AddConstraint(
            model_name='offergroupitem',
            constraint=models.UniqueConstraint(condition=models.Q(('combo__isnull', False)), fields=('offer_group', 'combo'), name='uniq_offeritem_group_combo'),
        ),
        migrations.AddConstraint(
            model_name='wantbid',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_listing__isnull', False), ('combo__isnull', True)), models.Q(('event_listing__isnull', True), ('combo__isnull', False)), _connector='OR'), name='wantbid_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='wantbid',
            constraint=models.UniqueConstraint(condition=models.Q(('event_listing__isnull', False)), fields=('user', 'event', 'event_listing'), name='uniq_wantbid_user_event_listing'),
        ),
        migrations.AddConstraint(
            model_name='wantbid',
            constraint=models.UniqueConstraint(condition=models.Q(('combo__isnull', False)), fields=('user', 'event', 'combo'), name='uniq_wantbid_user_event_combo'),
        ),
        migrations.AddConstraint(
            model_name='wantgroupitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_listing__isnull', False), ('combo__isnull', True)), models.Q(('event_listing__isnull', True), ('combo__isnull', False)), _connector='OR'), name='wantitem_exactly_one_target'),
        ),
    ]
