# Generated by Django 5.2.15 on 2026-06-22 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_combo_comboitem'),
        ('trades', '0008_remove_wantbid_uniq_wantbid_user_event_listing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TAKE', 'Take (receive at most N)'), ('GIVE', 'Give (send at most N)')], max_length=4)),
                ('n', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_caps', to='events.tradeevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_caps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TradeCapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trades.tradecap')),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cap_memberships', to='events.combo')),
                ('event_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cap_memberships', to='events.eventlisting')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('event_listing__isnull', False), ('combo__isnull', True)), models.Q(('event_listing__isnull', True), ('combo__isnull', False)), _connector='OR'), name='capitem_exactly_one_target')],
            },
        ),
    ]
