# Generated by Django 5.2.15 on 2026-06-22 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_combo_comboitem'),
        ('trades', '0009_tradecap_tradecapitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tradecap',
            constraint=models.CheckConstraint(condition=models.Q(('n__gte', 1)), name='tradecap_n_gte_1'),
        ),
    ]
