# Generated by Django 5.2.15 on 2026-09-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_tradecap_tradecap_n_gte_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradecap',
            name='kind',
            field=models.CharField(choices=[('TAKE', 'Take (receive any N items)'), ('GIVE', 'Give (send any N items)')], max_length=4),
        ),
    ]
