# Generated by Django 5.1.15 on 2026-05-29 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_username', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('bgg_verified', models.BooleanField(default=False)),
                ('default_country', models.CharField(blank=True, max_length=10)),
                ('default_region', models.CharField(blank=True, max_length=20)),
                ('is_organizer', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
