# Generated by Django 5.2.15 on 2026-06-06 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('listing_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('condition', models.CharField(blank=True, choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='', max_length=16)),
                ('language', models.CharField(blank=True, default='', max_length=64)),
                ('edition', models.CharField(blank=True, default='', max_length=120)),
                ('sleeved', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('NONE', 'None'), ('SLEEVED', 'Sleeved')], default='UNKNOWN', max_length=16)),
                ('includes_expansions', models.TextField(blank=True, default='')),
                ('missing_components', models.TextField(blank=True, default='')),
                ('upgraded_components', models.TextField(blank=True, default='')),
                ('component_notes', models.TextField(blank=True, default='')),
                ('owner_notes', models.TextField(blank=True, default='')),
                ('trade_value_hint', models.CharField(blank=True, default='', max_length=120)),
                ('shipping_constraints', models.TextField(blank=True, default='')),
                ('pickup_available', models.BooleanField(default=False)),
                ('photo_urls', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESERVED', 'Reserved'), ('TRADED', 'Traded'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('board_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='catalog.boardgame')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
