# Generated by Django 5.2.15 on 2026-06-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='import_source',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='copy',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
