# Generated by Django 5.2.15 on 2026-06-10 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_boardgameversion'),
        ('copies', '0002_copy_import_source_copy_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='catalog.boardgameversion'),
        ),
    ]
