# Generated by Django 5.2.15 on 2026-06-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeassignment',
            name='item_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
