# Generated by Django 5.2.15 on 2026-06-22 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_combo_comboitem'),
        ('matching', '0005_settlementpayment'),
        ('trades', '0008_remove_wantbid_uniq_wantbid_user_event_listing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeassignment',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_assignments', to='events.combo'),
        ),
        migrations.AlterField(
            model_name='tradeassignment',
            name='event_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_assignments', to='events.eventlisting'),
        ),
        migrations.AddConstraint(
            model_name='tradeassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_listing__isnull', False), ('combo__isnull', True)), models.Q(('event_listing__isnull', True), ('combo__isnull', False)), _connector='OR'), name='assignment_exactly_one_target'),
        ),
    ]
