# Generated by Django 5.2.15 on 2026-06-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_tradeassignment_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrun',
            name='carried_over',
            field=models.BooleanField(default=False),
        ),
    ]
