# Generated by Django 5.2.15 on 2026-09-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_matchrun_carried_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrun',
            name='solver_input_checksum',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='matchrun',
            name='solver_result_checksum',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
