# Generated by Django 5.1.15 on 2026-05-29 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('NEW', 'New / sealed'), ('LIKE_NEW', 'Like new'), ('VERY_GOOD', 'Very good'), ('GOOD', 'Good'), ('ACCEPTABLE', 'Acceptable'), ('FOR_PARTS', 'For parts / incomplete')], default='VERY_GOOD', max_length=20)),
                ('language', models.CharField(blank=True, default='EN', max_length=10)),
                ('bgg_version_id', models.IntegerField(blank=True, null=True)),
                ('edition_note', models.CharField(blank=True, max_length=200)),
                ('completeness', models.CharField(choices=[('COMPLETE', 'Complete'), ('MISSING_MINOR', 'Missing minor components'), ('MISSING_MAJOR', 'Missing major components')], default='COMPLETE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.listing')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
