# Generated by Django 5.1.15 on 2026-05-29 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give_at_most', models.PositiveIntegerField(default=1)),
                ('get_at_least', models.PositiveIntegerField(default=1)),
                ('want_filters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='events.tradeevent')),
                ('offer_entries', models.ManyToManyField(related_name='offered_in_statements', to='events.evententry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_statements', to=settings.AUTH_USER_MODEL)),
                ('want_games', models.ManyToManyField(related_name='wanted_in_statements', to='catalog.game')),
            ],
        ),
    ]
