# Generated by Django 5.1.15 on 2026-05-29 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_json', models.JSONField(default=dict)),
                ('input_text', models.TextField(blank=True)),
                ('output_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('items_traded', models.IntegerField(blank=True, null=True)),
                ('users_trading', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='events.tradeevent')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='events.evententry')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_assignments', to=settings.AUTH_USER_MODEL)),
                ('match_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='matching.matchresult')),
            ],
        ),
    ]
